package com.example.entity;

import java.time.LocalDate;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="student")
public class Student {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String studentid;
	@DynamoDBAttribute
	private String name;
	@DynamoDBAttribute
	private String dob;
	@DynamoDBAttribute
	private String gender;
	@DynamoDBAttribute
	private String school;
	@DynamoDBAttribute
	private Course course;
	
	public Student() {}
	
	public Student(String studentid, String name, String dob, String gender, String school, Course course) {
		super();
		this.studentid = studentid;
		this.name = name;
		this.dob = dob;
		this.gender = gender;
		this.school = school;
		this.course = course;
	}
	
	
	public String getStudentid() {
		return studentid;
	}
	public void setStudentid(String studentid) {
		this.studentid = studentid;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDob() {
		return dob;
	}
	public void setDob(String dob) {
		this.dob = dob;
	}
	public String getGender() {
		return gender;
	}
	public void setGender(String gender) {
		this.gender = gender;
	}
	public String getSchool() {
		return school;
	}
	public void setSchool(String school) {
		this.school = school;
	}	
	public Course getCourse() {
		return course;
	}
	public void setCourse(Course course) {
		this.course = course;
	}
	@Override
	public String toString() {
		return "Student [studentid=" + studentid + ", name=" + name + ", dob=" + dob + ", gender=" + gender
				+ ", school=" + school + ", course=" + course + "]";
	}
	
}
