package com.example.entity;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="tb-teacherstudent")
public class Teacher {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String teacherid;
	@DynamoDBAttribute
	private String name;
	@DynamoDBAttribute
	private String school;
	@DynamoDBAttribute
	private List<String> subjects;
	@DynamoDBAttribute
	private List<Student> students;
	
	public Teacher() {
		
	}
	
	public Teacher(String teacherid, String name, String school, List<String> subjects, List<Student> students) {
		super();
		this.teacherid = teacherid;
		this.name = name;
		this.school = school;
		this.subjects = subjects;
		this.students = students;
	}

	public String getTeacherid() {
		return teacherid;
	}

	public void setTeacherid(String teacherid) {
		this.teacherid = teacherid;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSchool() {
		return school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public List<String> getSubjects() {
		return subjects;
	}

	public void setSubjects(List<String> subjects) {
		this.subjects = subjects;
	}

	public List<Student> getStudents() {
		return students;
	}

	public void setStudents(List<Student> students) {
		this.students = students;
	}

	@Override
	public String toString() {
		return "Teacher [teacherid=" + teacherid + ", name=" + name + ", school=" + school + ", subjects=" + subjects
				+ ", students=" + students + "]";
	}
	
	
	

}
