service: simple-aws-lambda
provider:
  name: aws
  runtime: java8
  profile: 
  region: ap-south-1
  timeout: 120 #default timeout is 6 sec
  memorySize: 1024
  iamRoleStatements:
    #- Effect: 'Allow'
    #  Action:
    #    - 's3:*'
    #  Resource:
    #    - 'arn:aws:s3:::${self:custom.serverlessBucket}/*'
    #    - !Join ['', ['arn:aws:s3:::', !Ref ServerlessDeploymentBucket, '/*']]
    - Effect: Allow
      Action: 
        - 'ssm:Get*'
      Resource:
        - '*'
    - Effect: Allow
      Action: 
        - 'ssm:List*'
      Resource:
        - '*'
    - Effect: Allow
      Action: 
        - 'ssm:Describe*'
      Resource:
        - '*'
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem      
      Resource:
        - 'arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.dynamodbtablename}'
#     - Effect: Allow
#       Action: 
#         - kms:Decrypt
#       Resource:
#         - arn:aws:ssm:ap-south-1:776024579834:key/alias/aws/ssm   

plugins:
  - serverless-pseudo-parameters

custom:
  serverlessBucket: serverless-custom-bucket
  stage: dev
  dynamodbtablename: tb-teacherstudent

package:
  artifact: target/TeacherStudentConnectLambda.jar

functions:  
  simpleHttp:
    handler: com.example.lambda.GetQualificationHandler
    events:
      - http:
          method: GET
          path: /getbs
  saveTeacher:
    handler: com.example.lambda.SaveTeacherHandler
    environment:
      LAMBDA_REGION: ap-south-1
    events:
      - http:
          method: POST
          path: /saveteacher